version: '3.9'
services:
  backend:
    build: ./Backend/
    command: uvicorn sql_app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: 
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./DB/Dockerfile
    ports:
      - "5432:5432"
  frontend:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    ports: 
      - "5173:5173"
